# Generated by Django 4.2.4 on 2023-09-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('brand_spectrum', 'Brand Spectrum'), ('client', 'Client'), ('influencer', 'Influencer')], default='brand_spectrum', max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('category', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], default='single', max_length=20)),
                ('children', models.PositiveIntegerField(default=0)),
                ('children_ages', models.CharField(blank=True, help_text="Comma-separated list of children's ages", max_length=255)),
                ('isRegistered', models.BooleanField(default=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='influencers', to='campaigns.campaign')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
