# Generated by Django 4.2.4 on 2023-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('category', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], default='single', max_length=20)),
                ('children', models.PositiveIntegerField(default=0)),
                ('children_ages', models.CharField(blank=True, help_text="Comma-separated list of children's ages", max_length=255)),
            ],
        ),
    ]
