# Generated by Django 4.2.4 on 2023-08-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='influencerregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
