# Generated by Django 4.2.4 on 2023-09-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerregistration',
            name='campaigns',
        ),
    ]
