# Generated by Django 4.2.4 on 2023-08-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_remove_influencerregistration_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerregistration',
            name='user_type',
            field=models.CharField(choices=[('brand_spectrum', 'Brand Spectrum'), ('client', 'Client'), ('influencer', 'Influencer')], default='brand_spectrum', max_length=15),
        ),
    ]
