# Generated by Django 4.2.4 on 2023-08-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_influencerregistration_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerregistration',
            name='user',
        ),
    ]
