# Generated by Django 4.2.4 on 2023-09-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_file'),
        ('influencers', '0004_remove_influencerregistration_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerregistration',
            name='campaigns',
            field=models.ManyToManyField(related_name='influencers_registration', to='campaigns.campaign'),
        ),
    ]
