# Generated by Django 4.2.4 on 2023-09-01 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencers', '0005_influencerregistration_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencer_registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
