# Generated by Django 4.2.4 on 2023-09-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_alter_influencerregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerregistration',
            name='isRegistered',
            field=models.BooleanField(default=False),
        ),
    ]
