# Generated by Django 4.2.4 on 2023-09-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brandmanagers', '0001_initial'),
        ('influencers', '0007_alter_influencerregistration_isregistered'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerregistration',
            name='brand_manager_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_manager_user', to='brandmanagers.brandmanager'),
        ),
    ]
