# Generated by Django 4.2.4 on 2023-09-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0008_influencerregistration_brand_manager_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerregistration',
            name='brand_manager_profile',
        ),
    ]
