# Generated by Django 4.2.4 on 2023-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0009_remove_influencerregistration_brand_manager_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerregistration',
            name='user_type',
            field=models.CharField(choices=[('brand_manager', 'Brand Manager'), ('client', 'Client'), ('influencer', 'Influencer')], default='brand_spectrum', max_length=15),
        ),
    ]
