# Generated by Django 4.2.4 on 2023-09-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_alter_influencerregistration_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='influencer_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile_user', to='influencers.influencerregistration'),
        ),
    ]
