# Generated by Django 4.2.4 on 2023-09-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_influencer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_influencer_registered',
            field=models.BooleanField(default=False),
        ),
    ]
