# Generated by Django 4.2.4 on 2023-09-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brandmanagers', '0002_remove_brandmanager_user'),
        ('accounts', '0003_customuser_is_influencer_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brand_manager_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_manager_user', to='brandmanagers.brandmanager'),
        ),
    ]
