# Generated by Django 4.2.4 on 2023-09-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_influencer_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='influencer_registration',
        ),
    ]
