# Generated by Django 4.2.4 on 2023-09-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brandmanagers', '0003_brandmanager_address_brandmanager_phone_number_and_more'),
        ('accounts', '0004_customuser_brand_manager_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brand_manager_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='brandmanagers.brandmanager'),
        ),
    ]
