# Generated by Django 4.2.4 on 2023-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('brand_manager', 'Brand Manager'), ('client', 'Client'), ('influencer', 'Influencer')], max_length=15),
        ),
    ]
