# Generated by Django 4.2.4 on 2023-09-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0011_alter_influencerregistration_user'),
        ('accounts', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='influencer_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_influencer_profile', to='influencers.influencerregistration'),
        ),
    ]
