# Generated by Django 4.2.4 on 2023-09-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='brand_manager',
        ),
        migrations.AddField(
            model_name='campaign',
            name='user_type',
            field=models.CharField(choices=[('brand_spectrum', 'Brand Spectrum'), ('client', 'Client'), ('influencer', 'Influencer')], default='Influencer', max_length=15),
        ),
    ]
