# Generated by Django 4.2.4 on 2023-09-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
