# Generated by Django 4.2.4 on 2023-09-06 09:36

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0002_remove_campaign_brand_manager_campaign_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='file',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='influencers',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='media_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
