# Generated by Django 4.2.4 on 2023-09-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_feedback_campaign_file_campaign_influencers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
