# Generated by Django 4.2.4 on 2023-09-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='file',
            field=models.FileField(default='mdedia/', upload_to='media/'),
        ),
    ]
