# Generated by Django 4.2.4 on 2023-09-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='file',
        ),
    ]
