# Generated by Django 4.2.4 on 2023-09-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_remove_campaign_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
