# Generated by Django 4.2.4 on 2023-09-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_brand_manager_influencercontentapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='brand_manager',
        ),
    ]
