# Generated by Django 4.2.4 on 2023-09-11 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0011_remove_campaign_brand_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brand_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
