# Generated by Django 4.2.4 on 2023-09-15 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0012_campaign_brand_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='user_type',
            field=models.CharField(choices=[('brand_manager', 'Brand Manager'), ('client', 'Client'), ('influencer', 'Influencer')], default='Influencer', max_length=15),
        ),
        migrations.CreateModel(
            name='InfluencerContentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='content_images/')),
                ('content_video', models.FileField(blank=True, null=True, upload_to='content_videos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
