# Generated by Django 4.2.4 on 2023-09-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandmanagers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmanager',
            name='user',
        ),
    ]
