# Generated by Django 4.2.4 on 2023-09-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandmanagers', '0002_remove_brandmanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmanager',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandmanager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
