# Generated by Django 4.2.4 on 2023-09-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandmanagers', '0003_brandmanager_address_brandmanager_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmanager',
            name='user_type',
            field=models.CharField(choices=[('brand_spectrum', 'Brand Spectrum'), ('client', 'Client'), ('influencer', 'Influencer')], default='brand_manager', max_length=15),
        ),
    ]
