# Generated by Django 4.2.4 on 2023-09-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandmanagers', '0005_alter_brandmanager_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmanager',
            name='email',
            field=models.EmailField(max_length=225, null=True),
        ),
    ]
